# Generated by Django 4.2.11 on 2024-12-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_language',
        ),
    ]
