# Generated by Django 5.1.3 on 2025-01-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_lesson_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='current_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translationexercise',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
