# Generated by Django 5.1.3 on 2025-01-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_challenge_points_placementtest_current_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('required_points', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usertranslationattempt',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='usertranslationattempt',
            name='user',
        ),
        migrations.CreateModel(
            name='LLMGeneratedQuestionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('source_language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], max_length=50)),
                ('target_language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], max_length=50)),
                ('points', models.PositiveIntegerField(default=10)),
                ('sentence', models.TextField()),
                ('question', models.TextField()),
                ('correct_answer', models.TextField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_generated_question_exercises', to='learning.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FillInTheBlankExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('source_language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], max_length=50)),
                ('target_language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], max_length=50)),
                ('points', models.PositiveIntegerField(default=10)),
                ('sentence', models.TextField()),
                ('missing_word', models.CharField(max_length=255)),
                ('translation_of_missing_word', models.CharField(max_length=255)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_the_blank_exercises', to='learning.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('source_language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], max_length=50)),
                ('target_language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], max_length=50)),
                ('points', models.PositiveIntegerField(default=10)),
                ('sentence', models.TextField()),
                ('correct_translation', models.TextField()),
                ('choices', models.JSONField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_exercises', to='learning.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReorderTranslationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('source_language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], max_length=50)),
                ('target_language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], max_length=50)),
                ('points', models.PositiveIntegerField(default=10)),
                ('sentence', models.TextField()),
                ('disordered_translation', models.TextField()),
                ('correct_translation', models.TextField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_translation_exercises', to='learning.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PlacementTest',
        ),
        migrations.DeleteModel(
            name='TranslationExercise',
        ),
        migrations.DeleteModel(
            name='UserTranslationAttempt',
        ),
    ]
