# Generated by Django 5.1.3 on 2025-01-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_mission_remove_usertranslationattempt_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reordertranslationexercise',
            name='disordered_translation',
        ),
        migrations.AddField(
            model_name='reordertranslationexercise',
            name='pieces',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
