# Generated by Django 5.1.3 on 2025-01-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_reordertranslationexercise_disordered_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
