# Generated by Django 5.1.3 on 2025-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_challenge_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillintheblankexercise',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='llmgeneratedquestionexercise',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoiceexercise',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reordertranslationexercise',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
