# Generated by Django 5.1.3 on 2025-01-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_fillintheblankexercise_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillintheblankexercise',
            name='missing_word',
        ),
        migrations.RemoveField(
            model_name='fillintheblankexercise',
            name='translation_of_missing_word',
        ),
        migrations.AddField(
            model_name='fillintheblankexercise',
            name='missing_words',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fillintheblankexercise',
            name='translation_of_sentence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
