# Generated by Django 5.1.3 on 2025-01-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_remove_fillintheblankexercise_missing_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmgeneratedquestionexercise',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
