# Generated by Django 4.2.17 on 2025-01-12 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_llmgeneratedquestionexercise_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.mission'),
        ),
    ]
